### ISSUE TITLE
解决设置的外部数据源，不同用户会相互覆盖的问题

### ISSUE THREAD

**Issue by Lindsaylin** [byzer-org/byzer-notebook#102]

**Comment by Lindsaylin** [comment]
设置的外部数据源，不同用户会相互覆盖。需要做个判断，连接不存在的时候 ，再让用户创建
![WechatIMG167](https://user-images.githubusercontent.com/83326375/157416230-2c77de90-b375-4782-af76-b64ca60965c5.png)
![WechatIMG165](https://user-images.githubusercontent.com/83326375/157416255-fd2a403d-84ef-40a8-85ec-978dc347244e.png)

**Comment by chengwang15** [comment]
需要设计的部分
- 连接名需要加用户名前缀
- engine 的状态展示
