### ISSUE TITLE
当一个csv文件很大的时候，在notebook端load数据，几乎显示不出来数据。需要手动增加limit才能访问数据

### ISSUE THREAD

**Issue by chaozwn** [byzer-org/byzer-notebook#111]
数据拉取的时候，是否应该自动限制条数。不应该让我们手动增加!emptyTable
![13d8809c59ebb609b1089e557679d26](https://user-images.githubusercontent.com/51357674/159615598-543b8afb-622b-4067-b23f-469aed3a872d.png)

**Comment by chaozwn** [comment]
限制条数应该从5000，改到100或者500

**Comment by ZhengshuaiPENG** [comment]
请参考 [Notebook 手册安装配置一节](https://docs.byzer.org/#/byzer-notebook/zh-cn/installation/install_uninstall),可以通过调整的参数来控制返回的数据行数 `notebook.job.output-size` , 默认值1000
