### ISSUE TITLE
优化 byzer notebook 的部署和启动

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-notebook#115]
期望优化的点：

1. 命令行打包的目录需要进行优化，二进制包中添加 bin 的folder，启动命令移动到 bin 目录下，当前散落在安装主体目录
2. 封装一个 notebook.sh, 在其中封装如下几个命令
    - `notebook.sh start`
    - `notebook.sh stop`
    - `notebook.sh restart` 
4. 启动的时候需要在 bin 目录下生成当前进程的 pid，用于做停止功能和重复进程启动检查
5. 目前的启动脚本没有做相应的依赖检查，启动的时候需要做下述检查
    - mysql 依赖的检查
    - java 的检查
    - byzer engine 的检查
    - 当前是否存在已有进程， 根据 pid 的做 lock 检测
   要求每一个环境依赖检查，需要有明显的报错原因和提示，任何一项检测失败都不应该执行启动
6. 目前需要手动创建 db 库 notebook， 需要将此步骤自动化
7. 分离脚本启动的日志输出，和 notebook 本身的日志数据，示例如下
```
|-- logs
    |-- notebook.out   ## 启动过程中输出关键的经过整理的信息 
    |-- notebook.error ## 启动过程中所有的日志
    |-- notebook.logs ## notebook 应用本身的日志
    |-- access_logs ##  http 请求的 access logs 
```
启动失败的情况，可以在 notebook.out 中查看经过封装的失败提示，可以在 notebook.error 中查看到详细的失败的 stacktrace
8. conf 目录里需要加入日志等级的配置文件，日志需要根据大小做切分

**Comment by ZhengshuaiPENG** [comment]
estimate 3day， 参考 KAP 的script 脚本实现

**Comment by AdmondGuo** [comment]
#119 
#120 
#121 
#122 
#123
