### ISSUE TITLE
Byzer engine 重启，外部数据源需要手动测试链接后才能正常

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-notebook#116]
![middle_img_v2_7093acc8-97a1-46e5-be13-edbbde76cb6g](https://user-images.githubusercontent.com/11333496/160232722-219cce42-f59e-41f1-94a2-275797009f47.jpg)

对于外部数据源，notebook 在engine 重启后，是否可以自动重新链接外部数据源

**Comment by chaozwn** [comment]
就是重启engine之后，在此执行执行的代码，代码里面直接load jdbc.ml.库名，然后报错，找不到jdbc.
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/51357674/160232997-9d52f16b-f1a3-40cf-ad5c-336a17a5e2d5.png">

**Comment by chaozwn** [comment]
解决问题的方法，设置里面，重新手动测试连接，然后显示连接成功，就恢复了。

**Comment by ZhengshuaiPENG** [comment]
设计的思路：
1. notebook 和 engine 添加心跳检测机制，心跳时间可配，默认 180 s 间隔
2. 检测到engine 断连后，前端需要有一些状态显示，当前 engine 不可用，（考虑前端加入手动按钮，尝试重连 engine）
3. engine 重连后，自动刷新外部数据源连接

estimate 5day
