### ISSUE TITLE
 启动Notebook连接数据库时需要明显提示

### ISSUE THREAD

**Issue by chncaesar** [byzer-org/byzer-notebook#137]
K8S部署，无法连接数据库时，导致 pod 无法启动，非常难以debug。目前的实现简直是新手杀手。用户群里，不止一个用户提过这个问题。

目前的设计，MySQL 和 byzer-lang 无法连接，notebook 都无法启动。建议： 无法连接时，给出连接信息，帮助用户诊断。特别是，K8S 环境，连接信息使用 configmap/secret/VolumeMount 环境变量等多种方式传入，使得出错点较多。Notebook 给出更多信息，能提高问题诊断效率。

要求： 除了数据库外，包括引擎的连接等信息，都需要良好的报错出来

**Comment by ZhengshuaiPENG** [comment]
estimate 1d
