### ISSUE TITLE
需要支持 Notebook 和其他服务之间的互信 token 设置

### ISSUE THREAD

**Issue by chncaesar** [byzer-org/byzer-notebook#159]
当前情况 token 是通过 jwt 代码 NotebookApiService.getNotebook 代码中使用写死私钥 parse jwt token。这导致第三方调用 notebook Open APi时，使用同样 jwt token，且不可更改。

需要让用户通过参数进行配置这个 token，来保证不同 notebook 在实现跨应用互信时的 token 不同

**Comment by ZhengshuaiPENG** [comment]
新增参数配置 `notebook.services.communication.token`, 该配置是可以通过在其他应用中需要和 notebook 联动时，配置相同的 token，来完成服务端的通信认证
