### ISSUE TITLE
JDBC 数据源添加 SqlServer 时连接报错

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-notebook#170]
**Reproduce Step**：

1. 在 Byzer Notebook 中的设置中添加 sqlserver（或其他非 mysql 的db）数据源

2. 填入参数，参数可参考如下

 
```
CONNECT jdbc where
url="${JDBC_URL}"
and driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
and databaseName = "${DB_NAME}"
and user= "${USER_NAME}"
and password = "${PASSWORD}"
and encrpty="true"
and trustServerCertificate="true"
as mssql_db_poc;
```
 
3. 检测连接时就一直报错

 

**原因分析**

Byzer Notebook 的添加数据源的功能中是依靠引擎的 SQLJDBC ET 来实现的，该 ET 实现的过于简单，只传递了部分参数，对于其他的参数都没有办法传递，导致通过 SQLJDBC ET 实现的功能都没有办法支持非 mysql 的数据库 （比如 load jdbc 语句中的 direct query）

 

**预期**

- 功能表现预期：Notebook 配置 sqlserver 功能连接正常

- SQLJDBC ET 可以动态处理传入的参数，来支持不同的 jdbc 完成 direct query 的功能实现 

**注意**, 此issue需要更改 Byzer 引擎中 SQLJDBC 的实现

**Comment by ZhengshuaiPENG** [comment]
关联的 byzer-lang issue：https://github.com/byzer-org/byzer-lang/issues/1816

**Comment by wangcheng15** [comment]
#### Test:
- 以图示参数测试链接并保存
![image](https://user-images.githubusercontent.com/66863386/187331768-36aaa6fb-de33-4781-84d3-0915008f8524.png)
![image](https://user-images.githubusercontent.com/66863386/187331978-fd9c795b-50d4-47c9-bc6a-11f760ec4dd7.png)
- 在 notebook 中使用保存的连接获取数据
![image](https://user-images.githubusercontent.com/66863386/187332270-c30740bf-b732-44d4-a4c5-c4dbe47d104d.png)

#### Result:
- SQLserver 连接正常
![image](https://user-images.githubusercontent.com/66863386/187331978-fd9c795b-50d4-47c9-bc6a-11f760ec4dd7.png)
- 获取的数据正确
![image](https://user-images.githubusercontent.com/66863386/187332210-29eb3c25-6a7f-49b0-8abe-a38db3a9f6f1.png)

测试通过
