### ISSUE TITLE
Notebook 中需要能够将 cell 执行的日志回显至前端

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/byzer-notebook#79]
现在 Notebook 在执行 cell 中的代码块时，无法实时回显日志，会造成比较大的困扰，比如不知道执行的进度，关键日志也无法看到，希望可以在 notebook 中实现日志回显的功能，设计一个前后端日志交互的规范，可以通过标准的方式自动完成在代码中打印的日志直接回显到 notebook 前端

**Comment by chncaesar** [comment]
io.kyligence.notebook.console.service.JobService#getJobLog
