### ISSUE TITLE
[FeatureRequest] Byzer Notebook support export byzer script for byzer-cli run

### ISSUE THREAD

**Issue by chaozwn** [byzer-org/byzer-notebook#91]
support byzer notebook export byzer script for run.

eg. byzer run ....

![image](https://user-images.githubusercontent.com/51357674/155991217-ac187f6a-3233-49c9-8b12-27689d9f2122.png)

**Comment by chengwang15** [comment]
- 关联 Issue：https://github.com/byzer-org/byzer-notebook-vue/issues/150
